//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBIO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio
    {
        public int idNegocio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<int> idArticulo { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> idVenta { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
